language: ruby

services:
  - docker

script:
  - docker-compose up -d
  - docker-compose run -e "RAILS_ENV=test" web bin/rake db:create db:migrate
  - docker-compose run -e "RAILS_ENV=test" web bin/rake test