name: Ruby

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
    - name: Install dependencies
      run: bundle install
    - name: Run tests in docker
      run: 
        - docker-compose up -d
        - docker-compose run -e "RAILS_ENV=test" web bin/rake db:create db:migrate
        - docker-compose run -e "RAILS_ENV=test" web bin/rake test
